apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
  type: ClusterIP
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: web