apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "basic-bitcoin-forecast"
  namespace: default
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  predictor:
    serviceAccountName: sa-s3
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: s3://mlflow/1/8207a36e46c24039b993b96f16bcc185/artifacts/model
