apiVersion: v1
kind: Secret
metadata:
  name: sa-s3
  annotations:
     serving.kserve.io/s3-endpoint: mlflow-minio.mlflow:9000 # replace with your s3 endpoint e.g minio-service.kubeflow:9000 
     serving.kserve.io/s3-usehttps: "0" # by default 1, if testing with minio you can set to 0
     #serving.kserve.io/s3-region: "us-east-2"
     #serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: mlflow
  AWS_SECRET_ACCESS_KEY: mlflow123
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3
  namespace: default
secrets:
- name: sa-s3