apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: stateful-fit
spec:
  broker: crypto-prediction
  filter:
    attributes:
      type: cluster.local.aggregated_BTC/USD
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: el-stateful-fit-trigger