apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    run: el-stateful-fit-trigger
  name: el-stateful-fit-trigger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: el-stateful-fit-trigger
  template:
    metadata:
      labels:
        run: el-stateful-fit-trigger
    spec:
      containers:
      - image: docker.io/piepra/el-stateful-fit-trigger:1.3
        imagePullPolicy: Always
        name: el-stateful-fit-trigger
        ports:
        - containerPort: 5000
          protocol: TCP
