apiVersion: v1
kind: Service
metadata:
  name: el-stateful-fit-trigger
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    run: el-stateful-fit-trigger
  type: ClusterIP
