apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  params:
  - name: repo-url
    value: https://github.com/PiePra/Realtime-MLOps
  - name: image-reference
    value: docker.io/piepra/data-service:1.0
  - name: context-reference
    value: ./demonstration/apps/data-service/