
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "bitcoin-forecast-new"
  namespace: default
  labels:
    networking.knative.dev/visibility: cluster-local
spec:
  transformer:
    containers:
    - image: piepra/feast-transformer:0.4
      name: crypto-container
      command:
      - "python"
      - "app/app.py"
      args:
      - --feast_serving_url
      - feature-store-feature-server.feast.svc.cluster.local:6566
      - --entity_ids
      - "BTC/USD"
      - --feature_refs
      - "crypto_stats:open"
      - "crypto_stats:high"
      - "crypto_stats:low"
      - "crypto_stats:close"
      - --protocol
      - v2
  predictor:
    serviceAccountName: sa-s3
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: s3://mlflow/1/7b683d9578a548a792292bb690da9fd5/artifacts/model
