apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: default
spec:
  ports:
  - name: service
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: data-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    run: data-service
  name: data-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: data-service
  template:
    metadata:
      labels:
        run: data-service
    spec:
      containers:
      - image: docker.io/piepra/data-service:1.2
        imagePullPolicy: Always
        name: data-service
        ports:
        - containerPort: 5000
          protocol: TCP
