resources:
- namespace.yaml
- postgres.yaml
helmCharts:
- name: minio
  repo: https://charts.bitnami.com/charts
  version: 11.10.2
  releaseName: mlflow
  namespace: mlflow
  valuesInline: 
    auth:
      rootUser: mlflow
      rootPassword: mlflow123
    defaultBuckets: mlflow
- name: mlflow
  repo: https://community-charts.github.io/helm-charts
  version: 0.7.8
  releaseName: mlflow
  namespace: mlflow
  valuesInline:
      artifactRoot:
        s3:
          bucket: mlflow
          awsAccessKeyId: mlflow
          enabled: true
          awsSecretAccessKey: mlflow123
      backendStore:
        databaseMigration: true
        postgres:
          user: mlflow
          password: mlflow
          database: mlflow
          enabled: true
          host: postgres-postgresql
      extraEnvVars:
        MLFLOW_S3_ENDPOINT_URL: http://mlflow-minio.mlflow:9000
      service:
        port: 80
