---
# Source: mlflow/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    helm.sh/chart: mlflow-1.0.8
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
    app.kubernetes.io/version: "1.9.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
---
# Source: mlflow/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
  labels:
    helm.sh/chart: mlflow-1.0.8
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/instance: mlflow
    app.kubernetes.io/version: "1.9.1"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mlflow
      app.kubernetes.io/instance: mlflow
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mlflow
        app.kubernetes.io/instance: mlflow
    spec:
      
      securityContext:
        runAsUser: 0
      containers:
        - name: mlflow
          image: "larribas/mlflow:1.9.1"
          imagePullPolicy: IfNotPresent
          command: [
              "mlflow",
              "server",
              "--host", "0.0.0.0",
              "--port", "5000",
              "--default-artifact-root", "s3://minio.mlflow.svc.cluster.local/mlflow",
              "--backend-store-uri", 'postgresql+psycopg2://mlflow:mlflow@postgres-postgresql.mlflow.svc.cluster.local:5432/mlflow'
          ]
          ports:
            - name: http
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 3
            successThreshold: 2
            failureThreshold: 6
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 600
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
            timeoutSeconds: 5
          resources:
            {}
      volumes:
        - name: mlflow
          configMap:
            name: mlflow
