resources:
- namespace.yaml
- postgres.yaml
- redis.yaml
helmCharts:
- name: feast-feature-server
  repo: https://feast-helm-charts.storage.googleapis.com
  version: 0.24.1
  releaseName: feature-store
  namespace: feast
  valuesInline:
    feature_store_yaml_base64:  cHJvamVjdDogZmVhdHVyZV9zdG9yZQojIEJ5IGRlZmF1bHQsIHRoZSByZWdpc3RyeSBpcyBhIGZpbGUgKGJ1dCBjYW4gYmUgdHVybmVkIGludG8gYSBtb3JlIHNjYWxhYmxlIFNRTC1iYWNrZWQgcmVnaXN0cnkpCiMgVGhlIHByb3ZpZGVyIHByaW1hcmlseSBzcGVjaWZpZXMgZGVmYXVsdCBvZmZsaW5lIC8gb25saW5lIHN0b3JlcyAmIHN0b3JpbmcgdGhlIHJlZ2lzdHJ5IGluIGEgZ2l2ZW4gY2xvdWQKcmVnaXN0cnk6CiAgICByZWdpc3RyeV9zdG9yZV90eXBlOiBQb3N0Z3JlU1FMUmVnaXN0cnlTdG9yZQogICAgcGF0aDogZmVhc3RfcmVnaXN0cnkKICAgIGhvc3Q6IG9mZmxpbmUtc3RvcmUtcG9zdGdyZXNxbC5mZWFzdC5zdmMuY2x1c3Rlci5sb2NhbAogICAgcG9ydDogNTQzMgogICAgZGF0YWJhc2U6IGZlYXN0CiAgICBkYl9zY2hlbWE6IHB1YmxpYwogICAgdXNlcjogZmVhc3QKICAgIHBhc3N3b3JkOiBmZWFzdApwcm92aWRlcjogbG9jYWwKb25saW5lX3N0b3JlOgogICAgdHlwZTogcmVkaXMKICAgIGNvbm5lY3Rpb25fc3RyaW5nOiBvbmxpbmUtc3RvcmUtcmVkaXMtbWFzdGVyLmZlYXN0LnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzkscGFzc3dvcmQ9QU9WQWxNT2ZBdApvZmZsaW5lX3N0b3JlOgogICAgdHlwZTogcG9zdGdyZXMKICAgIGhvc3Q6IG9mZmxpbmUtc3RvcmUtcG9zdGdyZXNxbC5mZWFzdC5zdmMuY2x1c3Rlci5sb2NhbAogICAgcG9ydDogNTQzMgogICAgZGF0YWJhc2U6IGZlYXN0CiAgICBkYl9zY2hlbWE6IHB1YmxpYwogICAgdXNlcjogZmVhc3QKICAgIHBhc3N3b3JkOiBmZWFzdAplbnRpdHlfa2V5X3NlcmlhbGl6YXRpb25fdmVyc2lvbjogMg==
    transformation-service:
      enabled: false
    image:
      repository: piepra/feature-server-postgres
  pullPolicy: IfNotPresent
  tag: 0.24.1
